# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffer_handler

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FileDataList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FileDataList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFileDataList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FileDataList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FileDataList
    def Files(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from flatbuffer.FileData import FileData
            obj = FileData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FileDataList
    def FilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FileDataList
    def FilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def FileDataListStart(builder):
    builder.StartObject(1)

def Start(builder):
    FileDataListStart(builder)

def FileDataListAddFiles(builder, files):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(files), 0)

def AddFiles(builder, files):
    FileDataListAddFiles(builder, files)

def FileDataListStartFilesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFilesVector(builder, numElems):
    return FileDataListStartFilesVector(builder, numElems)

def FileDataListEnd(builder):
    return builder.EndObject()

def End(builder):
    return FileDataListEnd(builder)
