# This workflow will builds rust dependencies and uses clippy for linting
name: test-build-deploy-workflow

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read  

jobs:
  test_and_lint:    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy

    - name: Lint with Clippy (Errors Only)
      working-directory: server
      run: |
        cargo clippy -- -A warnings  # report only errors

  build_and_deploy:
    needs: test_and_lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image to ghcr
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ciaos:${{ github.sha }}
 
    - name: POST request to re-deploy on portainer webhook
      run: |
        curl -X POST https://docker.cialabs.org/api/stacks/webhooks/4e3fb43a-54dc-459a-be5a-36988796405e?BUILD_HASH=${{ github.sha }} -H "Content-Type: application/json" 
